name: Deploy to Dev

on:
  push:
    branches:
      - main  # triggers when changes are merged to main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder build step
        run: echo "No build steps needed"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # change to your Dev region

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.6  # or your desired Terraform version

      - name: Terraform Init
        working-directory: ./dev
        run: terraform init

      - name: Terraform Apply
        working-directory: ./dev
        run: terraform apply -auto-approve -var="env=dev"
